# Generated by Django 2.2.5 on 2019-11-10 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default='secret_key_for_pass_migratr', max_length=28),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SecretKeySave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key_saved', models.CharField(max_length=28)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
