# Generated by Django 2.2.5 on 2019-10-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0003_notificationbysms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationbysms',
            old_name='is_user',
            new_name='id_user',
        ),
    ]
