# Generated by Django 2.2.5 on 2019-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningAm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=160)),
                ('tuesday', models.CharField(max_length=160)),
                ('wednesday', models.CharField(max_length=160)),
                ('thursday', models.CharField(max_length=160)),
                ('friday', models.CharField(max_length=160)),
                ('saturday', models.CharField(max_length=160)),
                ('sunday', models.CharField(max_length=160)),
                ('notif_mo', models.BooleanField(default=False)),
                ('notif_tu', models.BooleanField(default=False)),
                ('notif_we', models.BooleanField(default=False)),
                ('notif_th', models.BooleanField(default=False)),
                ('notif_fr', models.BooleanField(default=False)),
                ('notif_sa', models.BooleanField(default=False)),
                ('notif_su', models.BooleanField(default=False)),
                ('text_notif_mo', models.TextField(null=True)),
                ('text_notif_tu', models.TextField(null=True)),
                ('text_notif_we', models.TextField(null=True)),
                ('text_notif_th', models.TextField(null=True)),
                ('text_notif_fr', models.TextField(null=True)),
                ('text_notif_sa', models.TextField(null=True)),
                ('text_notif_su', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Planning du midi de la semaine',
            },
        ),
        migrations.CreateModel(
            name='PlanningPm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=160)),
                ('tuesday', models.CharField(max_length=160)),
                ('wednesday', models.CharField(max_length=160)),
                ('thursday', models.CharField(max_length=160)),
                ('friday', models.CharField(max_length=160)),
                ('saturday', models.CharField(max_length=160)),
                ('sunday', models.CharField(max_length=160)),
                ('notif_mo', models.BooleanField(default=False)),
                ('notif_tu', models.BooleanField(default=False)),
                ('notif_we', models.BooleanField(default=False)),
                ('notif_th', models.BooleanField(default=False)),
                ('notif_fr', models.BooleanField(default=False)),
                ('notif_sa', models.BooleanField(default=False)),
                ('notif_su', models.BooleanField(default=False)),
                ('text_notif_mo', models.TextField(null=True)),
                ('text_notif_tu', models.TextField(null=True)),
                ('text_notif_we', models.TextField(null=True)),
                ('text_notif_th', models.TextField(null=True)),
                ('text_notif_fr', models.TextField(null=True)),
                ('text_notif_sa', models.TextField(null=True)),
                ('text_notif_su', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Planning du soir de la semaine',
            },
        ),
    ]
