# Generated by Django 2.2.3 on 2019-07-28 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=160)),
                ('tuesday', models.CharField(max_length=160)),
                ('wednesday', models.CharField(max_length=160)),
                ('thursday', models.CharField(max_length=160)),
                ('friday', models.CharField(max_length=160)),
                ('saturday', models.CharField(max_length=160)),
                ('sunday', models.CharField(max_length=160)),
                ('moment_day', models.CharField(max_length=2)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning de la semaine',
            },
        ),
    ]
