# Generated by Django 2.2.3 on 2019-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='notif_fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='notif_mo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='notif_sa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='notif_su',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='notif_th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='notif_tu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planning',
            name='notif_we',
            field=models.BooleanField(default=False),
        ),
    ]
