# Generated by Django 2.2.3 on 2019-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20190728_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='text_notif_mo',
            field=models.TextField(null=True),
        ),
    ]
