# Generated by Django 2.2.3 on 2019-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_planning_text_notif_mo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='text_notif_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='text_notif_sa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='text_notif_su',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='text_notif_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='text_notif_tu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='text_notif_we',
            field=models.TextField(null=True),
        ),
    ]
