# Generated by Django 2.2.5 on 2019-10-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20191003_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
