# Generated by Django 2.2.5 on 2019-10-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0006_auto_20191003_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningAm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=160)),
                ('tuesday', models.CharField(max_length=160)),
                ('wednesday', models.CharField(max_length=160)),
                ('thursday', models.CharField(max_length=160)),
                ('friday', models.CharField(max_length=160)),
                ('saturday', models.CharField(max_length=160)),
                ('sunday', models.CharField(max_length=160)),
                ('notif_mo', models.BooleanField(default=False)),
                ('notif_tu', models.BooleanField(default=False)),
                ('notif_we', models.BooleanField(default=False)),
                ('notif_th', models.BooleanField(default=False)),
                ('notif_fr', models.BooleanField(default=False)),
                ('notif_sa', models.BooleanField(default=False)),
                ('notif_su', models.BooleanField(default=False)),
                ('text_notif_mo', models.TextField(null=True)),
                ('text_notif_tu', models.TextField(null=True)),
                ('text_notif_we', models.TextField(null=True)),
                ('text_notif_th', models.TextField(null=True)),
                ('text_notif_fr', models.TextField(null=True)),
                ('text_notif_sa', models.TextField(null=True)),
                ('text_notif_su', models.TextField(null=True)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning du midi de la semaine',
            },
        ),
        migrations.CreateModel(
            name='PlanningPm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=160)),
                ('tuesday', models.CharField(max_length=160)),
                ('wednesday', models.CharField(max_length=160)),
                ('thursday', models.CharField(max_length=160)),
                ('friday', models.CharField(max_length=160)),
                ('saturday', models.CharField(max_length=160)),
                ('sunday', models.CharField(max_length=160)),
                ('notif_mo', models.BooleanField(default=False)),
                ('notif_tu', models.BooleanField(default=False)),
                ('notif_we', models.BooleanField(default=False)),
                ('notif_th', models.BooleanField(default=False)),
                ('notif_fr', models.BooleanField(default=False)),
                ('notif_sa', models.BooleanField(default=False)),
                ('notif_su', models.BooleanField(default=False)),
                ('text_notif_mo', models.TextField(null=True)),
                ('text_notif_tu', models.TextField(null=True)),
                ('text_notif_we', models.TextField(null=True)),
                ('text_notif_th', models.TextField(null=True)),
                ('text_notif_fr', models.TextField(null=True)),
                ('text_notif_sa', models.TextField(null=True)),
                ('text_notif_su', models.TextField(null=True)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning du soir de la semaine',
            },
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
